name: CI

on:
  push:
    branches: ["main", "work", "master"]
  pull_request:

jobs:
  rust:
    runs-on: ubuntu-22.04
    env:
      CARGO_TERM_COLOR: always
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libwebkit2gtk-4.0-dev \
            libgtk-3-dev \
            libayatana-appindicator3-dev \
            librsvg2-dev \
            libsoup2.4-dev \
            patchelf

      - name: Set up Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt

      - name: Cache cargo registry
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            src-tauri/target
          key: ${{ runner.os }}-cargo-${{ hashFiles('src-tauri/Cargo.lock') }}

      - name: Format check
        working-directory: src-tauri
        run: cargo fmt --all -- --check

      - name: Clippy
        working-directory: src-tauri
        run: cargo clippy --all-targets --all-features -- -D warnings -W clippy::pedantic

      - name: Tests
        working-directory: src-tauri
        run: cargo test

  macos-build:
    runs-on: macos-13
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: aarch64-apple-darwin

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm install

      - name: Build macOS bundle
        run: npm run tauri build -- --target universal-apple-darwin

      - name: Upload macOS artifact
        uses: actions/upload-artifact@v4
        with:
          name: macos-tauri-bundle
          path: src-tauri/target/release/bundle/macos
